flask_pro/flaskpro/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import (
    StringField,
    SubmitField,
    TextAreaField,
)
# this for validate the length of the field
from wtforms.validators import (
    DataRequired,
)


class CreatePostForm(FlaskForm):
    title = StringField('Title', validators=[
        DataRequired(), ])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Create Post')


class UpdatePostForm(FlaskForm):
    title = StringField('Title', validators=[
        DataRequired(), ])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Update Post')

flask_pro/flaskpro/posts/routes.py
from flask import (
    render_template,
    url_for,
    flash,
    redirect,
    request,
    abort,
    Blueprint,
)
from flask_login import (
    login_user,
    current_user,
    login_required,
)
from flaskpro import db
from flaskpro.models import Post, User
from flaskpro.posts.forms import (
    CreatePostForm,
    UpdatePostForm,
)


posts = Blueprint('posts', __name__)


@posts.route('/post/create', methods=['GET', 'POST'])
@login_required
def create_post():
    template_name = 'posts/post_create.html'
    form = CreatePostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data,
                    content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash(f'{post.title} has been successfully created.', 'success')
        return redirect(url_for('posts.post_list'))
    return render_template(template_name, title='Create new post', form=form, legend='Create New post')


@posts.route('/posts')
def post_list():
    template_name = 'posts/posts.html'
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(
        Post.created_date.desc()).paginate(page=page, per_page=3)
    return render_template(template_name, title='Post list', posts=posts)


@posts.route('/user/<string:username>')
def user_posts(username):
    template_name = 'posts/user_posts.html'
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(
        Post.created_date.desc()).paginate(page=page, per_page=3)
    return render_template(template_name, title='User Post list', posts=posts, user=user)


@posts.route('/post/<int:post_id>')
def post_detail(post_id):
    template_name = 'posts/post_detail.html'
    post = Post.query.get_or_404(post_id)
    return render_template(template_name, post=post, title=post.title)


@posts.route('/post/update/<int:post_id>', methods=['GET', 'POST'])
@login_required
def post_update(post_id):
    template_name = 'posts/post_update.html'
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
        flash('Please be a ware that you only allowed to update own post!')
    form = UpdatePostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash(f'{current_user.username.upper()}, Your current post has been updated', 'success')
        return redirect(url_for('posts.post_detail', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template(template_name, post=post, form=form, legend='Update Post')


@posts.route('/post/delete/<int:post_id>', methods=['POST'])
@login_required
def post_delete(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash(f'{current_user.username.upper()}, Your current post has ben deleted', 'success')
    return redirect(url_for('posts.post_list'))

flask_pro/flaskpro/templates/posts/post_create.html
{% extends 'base.html' %}


{% block content %}

<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<form method="POST" action="" class="form-horizontal">{{ form.hidden_tag() }}

			<h3 class="h3 text-muted">{{ legend }}</h3>
			<br>
			<div class="">
			  {{ form.title.label(class=" control-label") }}
			  {% if form.title.errors %}
			    {{ form.title(class="form-control is-invalid") }}
			    <div class="col-md-8 invalid-feedback">
			        {% for error in form.title.errors %}
			            <span class="alert-danger">{{error}}</span>
			        {% endfor %}
			    </div>
			  {% else %}
			      {{ form.title(class="form-control control-label") }}
			  {% endif %}
			</div>
		  
			<div class="">
			  {{ form.content.label(class=" control-label") }}
			  {% if form.content.errors %}
			    {{ form.content(class="form-control form-control-lg is-invalid") }}
			    <div class="col-md-8 invalid-feedback">
			        {% for error in form.content.errors %}
			            <span class="alert-danger">{{error}}</span>
			        {% endfor %}
			    </div>
			  {% else %}
			      {{ form.content(class="form-control control-label") }}
			  {% endif %}
			</div>
			<br>
			<div class="">
			  {{ form.submit(class="btn btn-block btn-primary") }}
			</div>
		  
		</form>
	</div>
</div>

{% endblock content %}

flask_pro/flaskpro/templates/posts/post_detail.html
{% extends 'base.html' %}


{% block content %}
<div class="row">
	<div class="col-md-8">
		<img src="{{ url_for('static', filename='images/profile_picture/' + post.author.user_image) }}" class="rounded img-thumbnail float-right" >
		<h4>{{ post.title }}</h4>
		<p>{{post.author.username}}</p>
		<strong>{{ post.created_date.strftime('%h, %d %Y | %H:%m') }}</strong>
		<p class="text-justify">{{ post.content }}</p>

		{% if current_user.is_authenticated and post.author == current_user %}
		<div>
			<a href="{{ url_for('posts.create_post') }}" class="btn btn-secondary btn-success">Create Post</a>
			<a href="{{ url_for('posts.post_update', post_id=post.id) }}" class="btn btn-secondary btn-info">
				Update
			</a>
			
			<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal">
				Delete
			</button>
			
		</div>
		{% endif %}
	</div>
</div>

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete Post</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary pr-2" data-dismiss="modal">Close</button> 

        <form action="{{ url_for('posts.post_delete', post_id=post.id) }}" method="POST">
        	<input class="btn btn-danger pl-2" type="submit"  value="Delete">
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

flask_pro/flaskpro/templates/posts/post_update.html
{% extends 'base.html' %}


{% block content %}
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<form method="POST" action="" class="form-horizontal">{{ form.hidden_tag() }}

			<h3 class="h3 text-muted">{{legend}}</h3>
			<br>
			<div class="">
			  {{ form.title.label(class=" control-label") }}
			  {% if form.title.errors %}
			    {{ form.title(class="form-control is-invalid") }}
			    <div class="col-md-8 invalid-feedback">
			        {% for error in form.title.errors %}
			            <span class="alert-danger">{{error}}</span>
			        {% endfor %}
			    </div>
			  {% else %}
			      {{ form.title(class="form-control control-label") }}
			  {% endif %}
			</div>
		  
			<div class="">
			  {{ form.content.label(class=" control-label") }}
			  {% if form.content.errors %}
			    {{ form.content(class="form-control form-control-lg is-invalid") }}
			    <div class="col-md-8 invalid-feedback">
			        {% for error in form.content.errors %}
			            <span class="alert-danger">{{error}}</span>
			        {% endfor %}
			    </div>
			  {% else %}
			      {{ form.content(class="form-control control-label") }}
			  {% endif %}
			</div>
			<br>
			<div class="">
			  {{ form.submit(class="btn btn-block btn-primary") }}
			</div>
		</form>
	</div>
</div>
{% endblock content %}

flask_pro/flaskpro/templates/posts/posts.html
{% extends 'base.html' %}


{% block content %}
<div class="row">
	<div class="col-md-8">
		<h3 class="text-center text-muted">
			Posts
		</h3>
		{% for post in posts.items %}
			<img src="{{ url_for('static', filename='images/profile_picture/' + post.author.user_image) }}" class="rounded img-thumbnail float-right" >
			<h4><a href="{{ url_for('posts.post_detail', post_id=post.id) }}">{{ post.title }}</a></h4>
			<a href="{{ url_for('posts.user_posts', username=post.author.username) }}">{{post.author.username}}</a>
			<strong>{{ post.created_date.strftime('%h, %d %Y | %H:%m') }}</strong>
			<p class="text-justify">{{ post.content }}</p>
		{% endfor %}

		{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
			{% if page_num %}
				{% if posts.page == page_num %}
					<a href="{{ url_for('posts.post_list', page=page_num) }}" class="btn btn-primary mb-4">
						{{ page_num }}
					</a>
				{% else %}
					<a href="{{ url_for('posts.post_list', page=page_num) }}" class="btn btn-outline-primary mb-4">
						{{ page_num }}
					</a>
				{% endif %}
			{% else %}
				...
			{% endif %}
		{% endfor %}
	</div>
</div>
{% endblock content %}

flask_pro/flaskpro/templates/posts/user_posts.html
{% extends 'base.html' %}


{% block content %}
<div class="row">
	<div class="col-md-8">
		<h3 class="text-center text-muted">
			Posted by {{user.username}} ({{posts.total}})
		</h3>
		{% for post in posts.items %}
			<img src="{{ url_for('static', filename='images/profile_picture/' + post.author.user_image) }}" class="rounded img-thumbnail float-right" >
			<h4><a href="{{ url_for('posts.post_detail', post_id=post.id) }}">{{ post.title }}</a></h4>
			<a href="{{ url_for('posts.user_posts', username=post.author.username) }}">{{post.author.username}}</a>
			<strong>{{ post.created_date.strftime('%h, %d %Y | %H:%m') }}</strong>
			<p class="text-justify">{{ post.content }}</p>
		{% endfor %}

		{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
			{% if page_num %}
				{% if posts.page == page_num %}
					<a href="{{ url_for('posts.post_list', page=page_num) }}" class="btn btn-primary mb-4">
						{{ page_num }}
					</a>
				{% else %}
					<a href="{{ url_for('posts.post_list', page=page_num) }}" class="btn btn-outline-primary mb-4">
						{{ page_num }}
					</a>
				{% endif %}
			{% else %}
				...
			{% endif %}
		{% endfor %}
	</div>
</div>
{% endblock content %}