flask_pro/flaskpro/models.py
from datetime import datetime

from itsdangerous import TimedJSONWebSignatureSerializer as Serializer

from flask import current_app
from flaskpro import db, login_manager
from flask_login import UserMixin

''' We create function as decorater to recognise the user loggedin
used for user is authenticated, user is active, anounues user and get id 
'''

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(30), unique=True, nullable=False)
    email = db.Column(db.String(60), unique=True, nullable=False)
    user_image = db.Column(db.String(50), nullable=False,
                           default='default.jpg')
    password = db.Column(db.String(60), nullable=False)
    posts = db.relationship('Post', backref='author', lazy=True)

    def get_reset_token(self, expires_sec=1800):
        s = Serializer(current_app.config['SECRET_KEY'], expires_sec)
        return s.dumps({'user_id': self.id}).decode('utf-8')

    @staticmethod
    def verify_reset_token(token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            user_id = s.loads(token)['user_id']
        except:
            return None
        return User.query.get(user_id)

    def __repr__(self):
        return f"User('{self.username}', '{self.email}', '{self.user_image}')"


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(120), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    content = db.Column(db.Text(800), nullable=False)
    created_date = db.Column(
        db.DateTime, nullable=False, default=datetime.utcnow)

    def __repr__(self):
        return f"Post('{self.title}', '{self.created_date}', '{self.author}')"

flask_pro/flaskpro/accounts/routes.py
from flask import (
    render_template,
    url_for,
    flash,
    redirect,
    request,
    Blueprint,
)
from flask_login import (
    login_user,
    current_user,
    logout_user,
    login_required,
)
from flaskpro import db, bcrypt
''' The models must imported after database created not before !!!! '''
from flaskpro.models import User, Post

from flaskpro.accounts.forms import (
    UserRegistrationForm,
    UserLoginForm,
    UpdateUserAccountForm,
    RequestResetForm,
    RestPasswordForm,
)

from flaskpro.accounts.utils import save_picture, send_reset_email


accounts = Blueprint('accounts', __name__)


@accounts.route('/account/register', methods=['GET', 'POST'])
def user_register():
    if current_user.is_authenticated:
        return redirect(url_for('settings.home'))
    template_name = 'registration/registration_form.html'
    form = UserRegistrationForm()
    if form.validate_on_submit():
        ''' We ducrypte the password '''
        hashed_pwd = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user = User(username=form.username.data,
                    email=form.email.data, password=hashed_pwd)
        ''' Adding user to the database '''
        db.session.add(user)
        db.session.commit()
        flash(f'You have been successfully registered. You are ready to login', 'success')
        return redirect(url_for('accounts.user_login'))
    context = {
        'title': 'Register',
    }
    return render_template(template_name, title='Register', form=form)


@accounts.route('/account/login', methods=['GET', 'POST'])
def user_login():
    if current_user.is_authenticated:
        return redirect(url_for('settings.home'))
    template_name = 'registration/login_form.html'
    form = UserLoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('settings.home'))
        else:
            flash('Unsuccessful , please check the your detail', 'danger')
    return render_template(template_name, title='Login', form=form)


@accounts.route('/account/logout')
def logout():
    logout_user()
    return redirect(url_for('settings.home'))


@accounts.route('/user/account', methods=['GET', 'POST'])
@login_required
def account():
    template_name = 'registration/user_account.html'
    form = UpdateUserAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.user_image = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been update!', 'success')
        return redirect(url_for('accounts.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    user_image = url_for(
        'static', filename='images/profile_picture/' + current_user.user_image)
    return render_template(template_name, title='account', user_image=user_image, form=form)


@accounts.route('/user/reset_password', methods=['GET', 'POST'])
def reset_request():
    template_name = 'registration/reset_request.html'
    if current_user.is_authenticated:
        return redirect(url_for('settings.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has ben send to your email address with, please follow the process', 'info')
        return redirect(url_for('accounts.user_login'))
    return render_template(template_name, title='Reset Password', form=form)


@accounts.route('/user/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    template_name = 'registration/reset_token.html'
    if current_user.is_authenticated:
        return redirect(url_for('settings.home'))
    user = User.verify_reset_token(token)
    if not user:
        flash(f'This token is expired or invalid', 'warning')
        return redirect(url_for('accounts.reset_request'))
    form = RestPasswordForm()
    if form.validate_on_submit():
        ''' We ducrypte the password '''
        hashed_pwd = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        ''' Adding user to the database '''
        user.password = hashed_pwd
        db.session.commit()
        flash(f'You password has been updated. You are ready to login', 'success')
        return redirect(url_for('accounts.user_login'))
    return render_template(template_name, form=form, title='Reset new password')

flask_pro/flaskpro/posts/routes.py
from flask import (
    render_template,
    url_for,
    flash,
    redirect,
    request,
    abort,
    Blueprint,
)
from flask_login import (
    login_user,
    current_user,
    login_required,
)
from flaskpro import db
from flaskpro.models import Post, User
from flaskpro.posts.forms import (
    CreatePostForm,
    UpdatePostForm,
)


posts = Blueprint('posts', __name__)


@posts.route('/post/create', methods=['GET', 'POST'])
@login_required
def create_post():
    template_name = 'posts/post_create.html'
    form = CreatePostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data,
                    content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash(f'{post.title} has been successfully created.', 'success')
        return redirect(url_for('posts.post_list'))
    return render_template(template_name, title='Create new post', form=form, legend='Create New post')


@posts.route('/posts')
def post_list():
    template_name = 'posts/posts.html'
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(
        Post.created_date.desc()).paginate(page=page, per_page=3)
    return render_template(template_name, title='Post list', posts=posts)


@posts.route('/user/<string:username>')
def user_posts(username):
    template_name = 'posts/user_posts.html'
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(
        Post.created_date.desc()).paginate(page=page, per_page=3)
    return render_template(template_name, title='User Post list', posts=posts, user=user)


@posts.route('/post/<int:post_id>')
def post_detail(post_id):
    template_name = 'posts/post_detail.html'
    post = Post.query.get_or_404(post_id)
    return render_template(template_name, post=post, title=post.title)


@posts.route('/post/update/<int:post_id>', methods=['GET', 'POST'])
@login_required
def post_update(post_id):
    template_name = 'posts/post_update.html'
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
        flash('Please be a ware that you only allowed to update own post!')
    form = UpdatePostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash(f'{current_user.username.upper()}, Your current post has been updated', 'success')
        return redirect(url_for('posts.post_detail', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template(template_name, post=post, form=form, legend='Update Post')


@posts.route('/post/delete/<int:post_id>', methods=['POST'])
@login_required
def post_delete(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash(f'{current_user.username.upper()}, Your current post has ben deleted', 'success')
    return redirect(url_for('posts.post_list'))

flask_pro/flaskpro/settings/routes.py
from flask import (
    Blueprint,
    render_template,
    request,
)
from flaskpro.models import Post


settings = Blueprint('settings', __name__)

''' 
route in flask use to map to different pages, and decorator in flask use to add 
additional functionality to existing function and in this case this a Prout decorator 
will handle all of the complicated back-end
'''


posts = [
    {
        'title': 'Python',
        'author': 'Dilshad Abdulla',
        'content': "route in flask use to map to different pages, and decorator in flask use to add\
                    additional functionality to existing function and in this case this a Prout decorator \
                    will handle all of the complicated back-end",
        'publish_date': 'November 11 2018'
    },
    {
        'title': 'Google',
        'author': 'Dilshad Abdulla',
        'content': "route in flask use to map to different pages, and decorator in flask use to add\
                    additional functionality to existing function and in this case this a Prout decorator \
                    will handle all of the complicated back-end",
        'publish_date': 'April 12 2016'
    },
    {
        'title': 'Djnago',
        'author': 'Dilshad Abdulla',
        'content': "route in flask use to map to different pages, and decorator in flask use to add\
                    additional functionality to existing function and in this case this a Prout decorator \
                    will handle all of the complicated back-end",
        'publish_date': 'January 3 2018'
    },
    {
        'title': 'Bootstrap',
        'author': 'Dilshad Abdulla',
        'content': "route in flask use to map to different pages, and decorator in flask use to add\
                    additional functionality to existing function and in this case this a Prout decorator \
                    will handle all of the complicated back-end",
        'publish_date': 'November 11 2018'
    },
    {
        'title': 'AWS',
        'author': 'Dilshad Abdulla',
        'content': "route in flask use to map to different pages, and decorator in flask use to add\
                    additional functionality to existing function and in this case this a Prout decorator \
                    will handle all of the complicated back-end",
        'publish_date': 'April 12 2016'
    },
    {
        'title': 'Restframework API',
        'author': 'Dilshad Abdulla',
        'content': "route in flask use to map to different pages, and decorator in flask use to add\
                    additional functionality to existing function and in this case this a Prout decorator \
                    will handle all of the complicated back-end",
        'publish_date': 'January 3 2018'
    }
]


@settings.route('/')
@settings.route('/home')
def home():
    template_name = 'index.html'
    return render_template(template_name, title='Home', posts=posts)


@settings.route('/about')
def about():
    template_name = 'about.html'
    return render_template(template_name, title='About us')

flask_pro/flaskpro/templates/about.html
{% extends 'base.html' %}
<br>
{% block content %}
<div class="container">
	<h3>Welcome to new framework Flast about page</h3>
</div>	
{% endblock content %}

flask_pro/flaskpro/templates/alert_message.html
<div class="col-md-6 col-md-offset-3">
{% with messages = get_flashed_messages(with_categories=true) %}
	{% if messages %}
		{% for category, message in messages %}
			<div class="alert alert-{{ category }}">
				{{ message }}
			</div>
		{% endfor %}
	{% endif %}
{% endwith %}
</div>

flask_pro/flaskpro/templates/base.html
{% include 'header.html' %}
{% include 'navbar.html' %}

<hr class="featurette-divider">

<div class="container">

{% include 'alert_message.html' %}

{% block content %}

{% endblock content %}
</div>

{% include 'footer.html' %}

flask_pro/flaskpro/templates/carousel.html
<!-- Carousel
   ================================================== -->
   <div id="myCarousel" class="carousel slide" data-ride="carousel">
     <!-- Indicators -->
     <ol class="carousel-indicators">
       <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
       <li data-target="#myCarousel" data-slide-to="1"></li>
       <li data-target="#myCarousel" data-slide-to="2"></li>
     </ol>
     <div class="carousel-inner" role="listbox">
       <div class="item active">
         <img class="first-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="First slide">
         <div class="container">
           <div class="carousel-caption">
             <h1>Example headline.</h1>
             <p>Note: If you're viewing this page via a <code>file://</code> URL, the "next" and "previous" Glyphicon buttons on the left and right might not load/display properly due to web browser security rules.</p>
             <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
           </div>
         </div>
       </div>
       <div class="item">
         <img class="second-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Second slide">
         <div class="container">
           <div class="carousel-caption">
             <h1>Another example headline.</h1>
             <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
             <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
           </div>
         </div>
       </div>
       <div class="item">
         <img class="third-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Third slide">
         <div class="container">
           <div class="carousel-caption">
             <h1>One more for good measure.</h1>
             <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
             <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
           </div>
         </div>
       </div>
     </div>
     <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
       <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
       <span class="sr-only">Previous</span>
     </a>
     <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
       <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
       <span class="sr-only">Next</span>
     </a>
   </div><!-- /.carousel -->

flask_pro/flaskpro/templates/footer.html
        </div> <!-- /container -->
    <hr>
</div>
<footer class="container-fluid">

    <div class="container" style="padding-bottom:0px;">
        <div class="row">
            <div class="col-md-4">
                <ul class="text-center">
                    <li><a href="" title="" class="fab fa-linkedin">Linkedin</a> </li>
                    <li><a href="" title="" class="">Twitter</a> </li>
                    <li><a href="" title="" class="">GitHub</a> </li>
                </ul>
            </div>
            <div class="col-md-4">
                <p class="text-center text-muted" style="padding-top: 40px;">&copy; 2016 Company, Inc.</p>
            </div>
            <div class="col-md-4">
                <ul class="text-center">
                    <li><a href="" title="" class="fab fa-facebook">facebook</a></li>
                    <li><a href="" title="" class="">Instagram</a> </li>
                    <li><a href="" title="" class="">Facetime</a> </li>
                </ul>
            </div>
        </div>
    </div>
    
</footer>



    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='bootstrap/js/holder.min.js') }}"></script>
    
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{{ url_for('static', filename='bootstrap/js/ie10-viewport-bug-workaround.js') }}"></script>
  </body>
</html>

flask_pro/flaskpro/templates/header.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{{ url_for('static', filename='images/student.ico') }}">

    {% if title %}
		<title>Flask {{title}}</title>
	{% else %}
		<title>Flask Home</title>
	{% endif %}

    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{{ url_for('static', filename='bootstrap/css/ie10-viewport-bug-workaround.css') }}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{{ url_for('static', filename='bootstrap/js/ie-emulation-modes-warning.js') }}"></script>


    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='bootstrap/css/carousel.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    {% block signin %}{% endblock signin %}
    
  </head>
<!-- NAVBAR
================================================== -->
<body>

flask_pro/flaskpro/templates/index.html
{% extends 'base.html' %}

{# include 'carousel.html' #}

{% block content %}
	
<!-- Example row of columns -->
<div class="row">
	<h3 class="text-center">Welcome to new framework Flask</h3>
	<h3 class="text-muted text-capitalize text-center">This posts are retrieved from created dictionary not db for testing process only</h3>
	{% for post in posts %}
	<div class="col-md-4">
		 <h2>{{post.title}}</h2>
		 <strong>{{post.author}}</strong>
		 <p>{{post.content}} </p>
		 <p><a class="btn btn-default" href="#" role="button">{{post.publish_date}} &raquo;</a></p>
	</div>
	{% endfor %}
</div>

<!-- </div> -->
	
{% endblock content %}

flask_pro/flaskpro/templates/models.html
<div class="container marketing">

      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-4">
          <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
          <h2>Heading</h2>
          <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->


      <!-- START THE FEATURETTES -->

      <hr class="featurette-divider">

flask_pro/flaskpro/templates/navbar.html
<div class="navbar-wrapper">
    <!-- <div class="container"> -->

        <nav class="navbar navbar-inverse navbar-static-top">
          	<div class="container">
	            <div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
	             	<a class="navbar-brand" href="{{ url_for('settings.home') }}">Flask Pro</a>
	            </div>
	            <div id="navbar" class="navbar-collapse collapse">
	              <ul class="nav navbar-nav">
	                <li class="active"><a href="{{ url_for('settings.home') }}">Home</a></li>
	                <li><a href="{{ url_for('settings.about') }}">About</a></li>
	                <li><a href="/contact">Contact</a></li>

	               
		            <li><a href="{{ url_for('posts.post_list') }}">Posts</a></li>
		            

	                <li class="dropdown">
	                  <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">User <span class="caret"></span></a>
	                  <ul class="dropdown-menu">
	                  	{% if current_user.is_authenticated %}
	                  		<li><a href="{{ url_for('accounts.logout') }}">Logout</a></li>
	                    	<li role="separator" class="divider"></li>
	                    	<li class="dropdown-header">Setting</li>
	                    	<li><a class="nav-item nav-link" href="{{ url_for('accounts.account') }}">Account</a></li>
	                    	<li><a class="nav-item nav-link" href="{{ url_for('posts.create_post') }}">
	                    		Create Post
	                    	</a></li>
	                    	<li><a class="nav-item nav-link" href="/change_password">
	                    		Change Password
	                    	</a></li>
	                    {% else %}
	                    	<li><a href="{{ url_for('accounts.user_login') }}">Login</a></li>
	                    	<li><a href="{{ url_for('accounts.user_register') }}">Register</a></li>
	                    {% endif %}
	                  </ul>
	                </li>
	              </ul>
	            </div>
          	</div>
        </nav>

    <!-- </div> -->
</div>